### 아티스트 정보 수집

In [1]:
import pandas as pd

all_chart = pd.read_csv('/Users/js/MMA/Melon_Music_Award/data/주간차트/melon_total.csv')
all_chart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32600 entries, 0 to 32599
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        32600 non-null  int64
 1   week        32600 non-null  object
 2   week_start  32600 non-null  object
 3   week_end    32600 non-null  object
 4   rank        32600 non-null  int64
 5   title       32600 non-null  object
 6   artist      32600 non-null  object
 7   album       32600 non-null  object
 8   like_cnt    32600 non-null  int64
dtypes: int64(3), object(6)
memory usage: 2.2+ MB

In [2]:
all_artists = all_chart['artist'].unique()

In [5]:
# 전체 차트 아티스트 수
len(all_artists)

416

In [6]:
# 이미 수집한 아티스트 정보
artist_info = pd.read_csv('/Users/js/MMA/Melon_Music_Award/data/artist_info_2025.csv')
artist_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   아티스트명   110 non-null    object
 1   국적      110 non-null    object
 2   활동년대    110 non-null    object
 3   활동장르    110 non-null    object
 4   데뷔      110 non-null    object
 5   멤버      53 non-null     object
 6   성별      110 non-null    object
 7   구성      110 non-null    object
dtypes: object(8)
memory usage: 7.0+ KB

In [11]:
all_artists = set(all_chart['artist'].unique())
existing = set(artist_info['아티스트명'])

missing = list(all_artists - existing)

In [25]:
len(missing)

306

In [15]:
from typing import Type


pd.DataFrame(missing, columns=['artist']).to_csv('missing_artists.csv', index=False)

In [27]:
missing_artists = pd.read_csv('/Users/js/MMA/Melon_Music_Award/code/missing_artists.csv')
missing_artists.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  306 non-null    object
dtypes: object(1)
memory usage: 2.5+ KB

In [19]:
artist_crawl = pd.read_csv('/Users/js/MMA/Melon_Music_Award/code/artist_info_crawled2.csv')
artist_crawl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  302 non-null    object
 1   국적      302 non-null    object
 2   활동유형    302 non-null    object
 3   활동장르    301 non-null    object
 4   데뷔(곡)   302 non-null    object
 5   멤버      74 non-null     object
dtypes: object(6)
memory usage: 14.3+ KB

In [22]:

def parse_activity_type(x):
    if pd.isna(x):
        return pd.Series(['unknown', 'unknown'])
    
    parts = [p.strip() for p in x.split(',')]
    
    gender = 'unknown'
    type_ = 'unknown'
    
    for p in parts:
        # 성별
        if p == '여성':
            gender = '여성'
        elif p == '남성':
            gender = '남성'
        elif p == '혼성':
            gender = '혼성'
        
        # 구성
        elif p == '솔로':
            type_ = '솔로'
        elif p == '그룹':
            type_ = '그룹'
    
    return pd.Series([gender, type_])

# 적용
artist_crawl[['성별', '구성']] = artist_crawl['활동유형'].apply(parse_activity_type)

In [23]:
artist_crawl.head()

,artist,국적,활동유형,활동장르,데뷔(곡),멤버,성별,구성
0,김태리,대한민국,"여성, 솔로","국내영화, 국내드라마, 발라드",2016.08.25,NaN,여성,솔로
1,닐로(Nilo),대한민국,"남성, 솔로",발라드,2015.09.14,NaN,남성,솔로
2,레드벨벳-아이린&슬기,대한민국,"여성, 그룹","댄스, R&B/Soul, 일렉트로니카",2020.07.06,"아이린 (IRENE) , 슬기 (SEULGI)",여성,그룹
3,양요섭,대한민국,"남성, 솔로","발라드, 국내드라마, R&B/Soul",2012.11.26,NaN,남성,솔로
4,유아 (오마이걸),대한민국,"여성, 솔로","댄스, 발라드, 국내드라마",2020.09.07,NaN,여성,솔로

In [24]:
artist_crawl['artist'].unique()

array(['김태리', '닐로(Nilo)', '레드벨벳-아이린&슬기', '양요섭', '유아 (오마이걸)', '포맨 (4MEN)',
       '신예영', '규현 (KYUHYUN)', '가비엔제이', '창모 (CHANGMO)', '조이 (JOY)',
       'XIA (준수)', '곽진언', '싹쓰리 (유두래곤, 린다G, 비룡)', 'LUCY',
       'WSG워너비 조별경연 (대청봉)', '노아주다 (noahjooda)', '브라운아이드걸스', '허성현 (rosy)',
       '몬스타엑스', '하동균', 'ZEROBASEONE (제로베이스원)', 'Sondia', 'MINO (송민호)',
       'NC.A', '윤딴딴', '민니 (MINNIE)', 'Apink (에이핑크)', '김진표', '이수 (엠씨더맥스)',
       'tripleS (트리플에스)', '한동근', '황치열', '이승윤', '하이라이트 (HIGHLIGHT)', '정경호',
       '죠지', '미연 (MIYEON)', '#안녕', 'GOT the beat', '잠골버스', '길구봉구',
       '세훈&찬열', '오마이걸 (OH MY GIRL)', '씨야', 'X1 (엑스원)', '호미들', '이상순',
       'Raiden', '존박', 'STAYC(스테이씨)', '바이브', '에릭남 (Eric Nam)',
       'Kep1er (케플러)', '카라', '휘인 (Whee In)', 'NSW yoon', 'MC몽',
       '윤민수(바이브)', '린', '효린', '이영현', 'V', 'WSG워너비(4FIRE)',
       '박봄 (Park Bom)', '송하예', '뉴이스트', '주호', '송가인', '2BIC(투빅)', '빈첸',
       '이소정', '릴보이 (lIlBOI)', '조정석', '헨리 (HENRY)', '빅마마', '펭수', '윤토벤',
       '거미 (GUMMY)', 'Zion.T', '정동하', '김연지', '지아', '개코', '윤건',
       'Mudd the student', '솔지', '노윤하', '런치', '이해리 (다비치)', '아샤트리', '환희',
       'San E (산이)', 'IZ*ONE (아이즈원)', '허용별 (허각, 신용재, 임한별)', '보이비', '윤미래',
       '제시 (Jessi)', '염따', 'V.O.S', '혁오 (HYUKOH)', '미도와 파라솔', '정은지',
       '2AM', '우원재', '권은비', 'MSG워너비(M.O.M)', '2PM', '엠씨더맥스 (M.C the MAX)',
       '이예준', '김재환', "소녀시대 (GIRLS' GENERATION)", '태양', '마미손',
       '주시크 (Joosiq)', 'WSG워너비 (가야G)', '신용재 (2F)', 'NCT 도재정', '던 (DAWN)',
       '라비 (RAVI)', '선예', 'PATEKO (파테코)', '순순희(기태)', '청하', '이석훈',
       '케이시 (Kassy)', 'Say Yes!', '조광일', '보라미유', '베이식 (Basick)', '장혜진',
       '찬열 (CHANYEOL)', '강민경 (다비치)', 'SHINee (샤이니)', '블루 (BLOO)',
       'ASH ISLAND', '시온', '유림', 'KCM', 'Red Velvet (레드벨벳)', '환불원정대',
       'HYNN (박혜원)', '라붐 (LABOUM)', "BE'O (비오)", 'Yyeon', '영탁', '적재',
       '김대명', 'Seori', '윤도 (YoonDo)', 'BewhY (비와이)', '수퍼비 (SUPERBEE)',
       '진', 'ITZY (있지)', '나얼', '테이', '유회승 (엔플라잉)', '헤이즈 (Heize)',
       '조현아 (어반자카파)', '마마무 (Mamamoo)', '볼빨간사춘기', '양다일', '주주 시크릿',
       '던말릭 (DON MALIK)', 'Zior Park', '이하이', '백아', 'NCT 127', '화곡동 청개구리',
       '하은 (포맨)', '에이치코드 (H:CODE)', '이우', '식케이 (Sik-K)', '권진아', 'NS 윤지',
       '정준일', '21학번', '디핵 (D-Hack)', '하현우 (국카스텐)', '태일 (TAEIL)', '안세하',
       '노을', '지민', '권순일 (어반자카파)', '에이프릴 (APRIL)', '케이윌', '자우림', 'RM',
       'WINNER', '김승민', 'MSG워너비', '리사 (LISA)', '장범준', 'Khundi Panda',
       '어반자카파', '나연 (TWICE)', '에일리(Ailee)', '딘딘 (DINDIN)', 'KOONTA (쿤타)',
       '전소미', '제이세라', '비룡', 'Paul Blanco', 'DEAN', '이홍기 (FT아일랜드)', '토요태',
       '샘김 (Sam Kim)', '츄 (CHUU)', '웬디 (WENDY)', '펀치 (Punch)', '박재범',
       '김세정', '송이한', 'TOIL', '스윙스', '이루', '숀 (SHAUN)', '경서', 'GRAY (그레이)',
       '백예린 (Yerin Baek)', '정효빈', '아넌딜라이트(Anandelight)', '선우정아',
       '로시 (Rothy)', 'NCT U', '래원 (Layone)', '백아연', '릴러말즈 (Leellamarz)',
       'WSG워너비 (오아시소)', '그루비룸 (GroovyRoom)', 'Woodie Gochild', '선미',
       '유연석', '이승기', '유산슬', '김필', 'sokodomo', '임한별', '경서 (경서예지)', 'SF9',
       '다이나믹 듀오', '이승철', '현아', '이선희', 'WSG워너비', '문별 (마마무)', '육성재', '박경',
       '한요한', '피아노맨', '전상근', '산들', '도영 (DOYOUNG)', 'Don Mills', '조장혁',
       '반하나', '가호 (Gaho)', '박진영', '비', '브레이브걸스', '김나영', '장덕철', 'KHAN',
       '저스디스 (JUSTHIS)', '머쉬베놈 (MUSHVENOM)', '탑현', '솔라 (마마무)', '전미도',
       '싸이 (PSY)', 'CHEEZE (치즈)', 'Agust D', '제이레빗(J Rabbit)',
       '코드 쿤스트 (CODE KUNST)', '김호중', 'Stray Kids (스트레이 키즈)', 'pH-1',
       '첸 (CHEN)', '백지영', '이수현', 'B.I', '수호 (SUHO)', '린다G', '쿠기 (Coogie)',
       '기리보이', 'MSG워너비(정상동기)', '에픽하이 (EPIK HIGH)', '소유 (SOYOU)',
       '미란이 (MIRANI)', 'YUNB', '이채연', 'dori', 'VIVIZ (비비지)',
       '빈지노 (Beenzino)', '벤', '이세계아이돌', 'SINCE', '원슈타인', '백현 (BAEKHYUN)',
       '진민호', '스탠딩 에그', '펀치넬로 (punchnello)', 'DAY6 (Even of Day)'],
      dtype=object)

In [30]:
missing = set(missing_artists['artist'].unique())
crawled = set(artist_crawl['artist'])

missing2 = list(missing - crawled)

In [31]:
missing2

['MSG워너비 TOP 8 (별루지, 김정수, 강창모, 정기석, 이동휘, 이상이, 박재정, 원슈타인)',
 '우효',
 '에스파파(S.Papa.)',
 '2am',
 '유두래곤']

In [32]:
df_crawl = pd.read_csv('/Users/js/MMA/Melon_Music_Award/code/artist_info_crawled2.csv')

In [33]:
df_crawl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306 entries, 0 to 305
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   artist  306 non-null    object
 1   국적      306 non-null    object
 2   활동유형    306 non-null    object
 3   활동장르    305 non-null    object
 4   데뷔(곡)   306 non-null    object
 5   멤버      75 non-null     object
dtypes: object(6)
memory usage: 14.5+ KB

In [35]:
# 활동유형 > 성별, 구성
df_crawl[['성별', '구성']] = df_crawl['활동유형'].apply(parse_activity_type)

In [36]:
df_crawl.head()

,artist,국적,활동유형,활동장르,데뷔(곡),멤버,성별,구성
0,김태리,대한민국,"여성, 솔로","국내영화, 국내드라마, 발라드",2016.08.25,NaN,여성,솔로
1,닐로(Nilo),대한민국,"남성, 솔로",발라드,2015.09.14,NaN,남성,솔로
2,레드벨벳-아이린&슬기,대한민국,"여성, 그룹","댄스, R&B/Soul, 일렉트로니카",2020.07.06,"아이린 (IRENE) , 슬기 (SEULGI)",여성,그룹
3,양요섭,대한민국,"남성, 솔로","발라드, 국내드라마, R&B/Soul",2012.11.26,NaN,남성,솔로
4,유아 (오마이걸),대한민국,"여성, 솔로","댄스, 발라드, 국내드라마",2020.09.07,NaN,여성,솔로

### df_crawl + artist_info

In [37]:
artist_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   아티스트명   110 non-null    object
 1   국적      110 non-null    object
 2   활동년대    110 non-null    object
 3   활동장르    110 non-null    object
 4   데뷔      110 non-null    object
 5   멤버      53 non-null     object
 6   성별      110 non-null    object
 7   구성      110 non-null    object
dtypes: object(8)
memory usage: 7.0+ KB

In [38]:
# 컬럼명 통일 (df_crawl의 'artist'를 '아티스트명'으로 변경)
df_crawl = df_crawl.rename(columns={'artist': '아티스트명', '데뷔(곡)': '데뷔'})

# 데이터 합치기 (위아래로 연결)
combined_df = pd.concat([artist_info, df_crawl], ignore_index=True)

합치기 완료!

In [39]:
combined_df.head()

,아티스트명,국적,활동년대,활동장르,데뷔,멤버,성별,구성,활동유형
0,로제 (ROSÉ),대한민국,"2010, 2020","록/메탈, POP, 발라드",2021.03.12,NaN,여성,솔로,NaN
1,aespa,대한민국,2020,"댄스, 일렉트로니카, R&B/Soul",2020.11.17,"카리나 (KARINA), 지젤 (GISELLE), 윈터 (WINTER), 닝닝 (N...",여성,그룹,NaN
2,제니 (JENNIE),대한민국,"2010, 2020","댄스, 국외드라마, POP",2018.11.12,NaN,여성,솔로,NaN
3,DAY6 (데이식스),대한민국,"2010, 2020","록/메탈, 댄스, 발라드",2015.09.07,"성진 (DAY6), Young K (DAY6), 원필 (DAY6), 도운 (DAY6)",남성,그룹,NaN
4,G-DRAGON,대한민국,"2000, 2010, 2020","댄스, 랩/힙합, 발라드",2009.08.18,NaN,남성,솔로,NaN

In [40]:
combined_df = combined_df.drop(columns=['활동유형', '활동년대'])
combined_df.head()

,아티스트명,국적,활동장르,데뷔,멤버,성별,구성
0,로제 (ROSÉ),대한민국,"록/메탈, POP, 발라드",2021.03.12,NaN,여성,솔로
1,aespa,대한민국,"댄스, 일렉트로니카, R&B/Soul",2020.11.17,"카리나 (KARINA), 지젤 (GISELLE), 윈터 (WINTER), 닝닝 (N...",여성,그룹
2,제니 (JENNIE),대한민국,"댄스, 국외드라마, POP",2018.11.12,NaN,여성,솔로
3,DAY6 (데이식스),대한민국,"록/메탈, 댄스, 발라드",2015.09.07,"성진 (DAY6), Young K (DAY6), 원필 (DAY6), 도운 (DAY6)",남성,그룹
4,G-DRAGON,대한민국,"댄스, 랩/힙합, 발라드",2009.08.18,NaN,남성,솔로

In [53]:
target_name = 'WSG워너비 조별경연 (대청봉)'
combined_df.loc[combined_df['아티스트명'] == target_name, '활동장르'] = '발라드'

In [54]:
combined_df.loc[combined_df['아티스트명']==target_name]

                 아티스트명    국적 활동장르          데뷔   멤버  성별  구성
125  WSG워너비 조별경연 (대청봉)  대한민국  발라드  2022.05.28  NaN  여성  그룹

In [55]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 416 entries, 0 to 415
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   아티스트명   416 non-null    object
 1   국적      416 non-null    object
 2   활동장르    416 non-null    object
 3   데뷔      416 non-null    object
 4   멤버      128 non-null    object
 5   성별      416 non-null    object
 6   구성      416 non-null    object
dtypes: object(7)
memory usage: 22.9+ KB

In [56]:
combined_df.to_csv('artist_info_final.csv', index=False, encoding='utf-8-sig')

In [57]:
df = pd.read_csv('artist_info_final.csv')

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 416 entries, 0 to 415
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   아티스트명   416 non-null    object
 1   국적      416 non-null    object
 2   활동장르    416 non-null    object
 3   데뷔      416 non-null    object
 4   멤버      128 non-null    object
 5   성별      416 non-null    object
 6   구성      416 non-null    object
dtypes: object(7)
memory usage: 22.9+ KB

In [59]:
df.head()

,아티스트명,국적,활동장르,데뷔,멤버,성별,구성
0,로제 (ROSÉ),대한민국,"록/메탈, POP, 발라드",2021.03.12,NaN,여성,솔로
1,aespa,대한민국,"댄스, 일렉트로니카, R&B/Soul",2020.11.17,"카리나 (KARINA), 지젤 (GISELLE), 윈터 (WINTER), 닝닝 (N...",여성,그룹
2,제니 (JENNIE),대한민국,"댄스, 국외드라마, POP",2018.11.12,NaN,여성,솔로
3,DAY6 (데이식스),대한민국,"록/메탈, 댄스, 발라드",2015.09.07,"성진 (DAY6), Young K (DAY6), 원필 (DAY6), 도운 (DAY6)",남성,그룹
4,G-DRAGON,대한민국,"댄스, 랩/힙합, 발라드",2009.08.18,NaN,남성,솔로