In [1]:
import pandas as pd

df = pd.read_csv("/Users/js/MMA/Melon_Music_Award/data/melon_artist_info.csv")

df.head()

,아티스트명,국적,활동유형,활동년대,활동장르,데뷔,멤버,생일
0,로제 (ROSÉ),대한민국,"여성, 솔로","2010, 2020","록/메탈, POP, 발라드",2021.03.12,NaN,NaN
1,aespa,대한민국,"여성, 그룹",2020,"댄스, 일렉트로니카, R&B/Soul",2020.11.17,"카리나 (KARINA), 지젤 (GISELLE), 윈터 (WINTER), 닝닝 (N...",NaN
2,제니 (JENNIE),대한민국,"여성, 솔로","2010, 2020","댄스, 국외드라마, POP",2018.11.12,NaN,NaN
3,DAY6 (데이식스),대한민국,"남성, 그룹","2010, 2020","록/메탈, 댄스, 발라드",2015.09.07,"성진 (DAY6), Young K (DAY6), 원필 (DAY6), 도운 (DAY6)",NaN
4,G-DRAGON,대한민국,"남성, 솔로","2000, 2010, 2020","댄스, 랩/힙합, 발라드",2009.08.18,NaN,1988.08.18

In [8]:
# 활동유형 => 성별, 구성
df['성별'] = df['활동유형'].str.split(',').str[0].str.strip()
df['구성'] = df['활동유형'].str.split(',').str[1].str.strip()

In [9]:
df_new = df.drop(columns=['생일','활동유형'])
df_new.head()

,아티스트명,국적,활동년대,활동장르,데뷔,멤버,성별,구성
0,로제 (ROSÉ),대한민국,"2010, 2020","록/메탈, POP, 발라드",2021.03.12,NaN,여성,솔로
1,aespa,대한민국,2020,"댄스, 일렉트로니카, R&B/Soul",2020.11.17,"카리나 (KARINA), 지젤 (GISELLE), 윈터 (WINTER), 닝닝 (N...",여성,그룹
2,제니 (JENNIE),대한민국,"2010, 2020","댄스, 국외드라마, POP",2018.11.12,NaN,여성,솔로
3,DAY6 (데이식스),대한민국,"2010, 2020","록/메탈, 댄스, 발라드",2015.09.07,"성진 (DAY6), Young K (DAY6), 원필 (DAY6), 도운 (DAY6)",남성,그룹
4,G-DRAGON,대한민국,"2000, 2010, 2020","댄스, 랩/힙합, 발라드",2009.08.18,NaN,남성,솔로

In [10]:
df_new.to_csv('artist_info.csv', index=False, encoding='utf-8-sig')